language: smalltalk
sudo: false
smalltalk: 
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - libssl1.0.0:i386
      - mongodb-org-server

script:
  - ln -s /lib/i386-linux-gnu/libcrypto.so.1.0.0 libcrypto.so
  - LD_LIBRARY_PATH=$PWD $SMALLTALK_CI_HOME/run.sh
